---
- name: Fetch all security rules from PAN-OS Firewall
  hosts: firewall
  gather_facts: no

  tasks:
    - name: Fetch all security rules
      paloaltonetworks.panos.panos_op:
        provider: '{{ provider }}'
        cmd: 'show running security-policy'
      register: result

    - name: Parse security rules XML
      community.general.xml:
        xmlstring: '{{ result.stdout_xml }}'
        xpath: '/response/result/member'
        content: text
      register: security_rules

    - name: Convert security rules to Markdown
      ansible.builtin.copy:
        content: |
          {% for rule in security_rules.matches %}
          - **Rule Name**: {{ rule.member.split("; index:")[0].strip('" ') }}
            - **From**: {{ rule.member | regex_search('from (\S+)') }}
            - **Source**: {{ rule.member | regex_search('source \[([^\]]+)\]') }}
            - **To**: {{ rule.member | regex_search('to (\S+)') }}
            - **Destination**: {{ rule.member | regex_search('destination ([^\;]+)') }}
            - **Action**: {{ rule.member | regex_search('action (\S+)') }}
          {% endfor %}
        dest: /path/to/security_rules.md
