---
- name: Fetch all security rules from PAN-OS Firewall
  hosts: '{{ target | default("firewall") }}'
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

    vsys: 'vsys1'
    rule_base: 'security'

  tasks:
    - name: Fetch all security rules
      paloaltonetworks.panos.panos_op:
        ip_address: '{{ device.ip_address }}'
        username: '{{ device.username }}'
        password: '{{ device.password }}'
        api_key: '{{ device.api_key }}'
        cmd: 'show running security-policy'
      register: result

    - name: Parse security rules XML
      community.general.xml:
        xmlstring: '{{ result.stdout_xml }}'
        xpath: '/response/result/member'
        content: text
      register: security_rules

    - name: Debug parsed security rules
      debug:
        var: security_rules

    - name: Convert security rules to Markdown
      ansible.builtin.copy:
        content: |
          {% for rule in security_rules.matches %}
          - **Rule Name**: {{ rule.member.split("; index:")[0].strip('" ') }}
            - **From**: {{ rule.member | regex_search('from (\S+)') }}
            - **Source**: {{ rule.member | regex_search('source \[([^\]]+)\]') }}
            - **To**: {{ rule.member | regex_search('to (\S+)') }}
            - **Destination**: {{ rule.member | regex_search('destination ([^\;]+)') }}
            - **Action**: {{ rule.member | regex_search('action (\S+)') }}
          {% endfor %}
        dest: /path/to/security_rules.md
