---
- name: Fetch all security rules from PAN-OS Firewall
  hosts: '{{ target | default("firewall") }}'
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

    vsys: 'vsys1'
    rule_base: 'security'

  tasks:
    - name: Fetch all security rules
      paloaltonetworks.panos.panos_op:
        ip_address: '{{ device.ip_address }}'
        username: '{{ device.username }}'
        password: '{{ device.password }}'
        api_key: '{{ device.api_key }}'
        cmd: 'show running security-policy'
      register: result

    - name: Parse security rules XML
      community.general.xml:
        xmlstring: '{{ result.stdout_xml }}'
        xpath: '/response/result/member'
        content: text
      register: security_rules

    - name: Debug parsed security rules
      debug:
        var: security_rules

    - name: Convert security rules to Markdown table
      ansible.builtin.copy:
        content: |
          | Rule Name | From | Source | To | Destination | Action |
          | --- | --- | --- | --- | --- | --- |
          {% for rule in security_rules.matches %}
          | {{ rule.member.split("; index:")[0].strip('" ') }} 
          | {{ rule.member | regex_search('from (\S+);') }} 
          | {{ rule.member | regex_search('source \[([^\]]+)\]') }} 
          | {{ rule.member | regex_search('to (\S+);') }} 
          | {{ rule.member | regex_search('destination ([^\;]+);') }} 
          | {{ rule.member | regex_search('action (\S+);') }} 
          {% endfor %}
        dest: ../configs/security_rules.md