---
- name: Fetch all security rules from PAN-OS Firewall
  hosts: '{{ target | default("firewall") }}'
  connection: local
  gather_facts: false

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

  tasks:
    - name: Fetch all security rules
      paloaltonetworks.panos.panos_op:
        provider: '{{ device }}'
        cmd: 'show running security-policy'
      register: result

    - name: Parse security rules XML
      community.general.xml:
        xmlstring: '{{ result.stdout_xml }}'
        xpath: '/response/result/member'
        content: text
      register: rules

    - name: Convert security rules to Markdown
      set_fact:
        rules_md: |
          | Rule Name | Source Zone | Destination Zone | Source Address | Destination Address | Action |
          |-----------|-------------|------------------|----------------|---------------------|--------|
          {% for rule in rules.matched %}
          | {{ rule.split(';')[0].strip('" ') }} | {{ rule.split('from')[1].split(';')[0].strip() }} | {{ rule.split('to')[1].split(';')[0].strip() }} | {{ rule.split('source')[1].split(';')[0].strip('[] ') }} | {{ rule.split('destination')[1].split(';')[0].strip() }} | {{ rule.split('action')[1].split(';')[0].strip() }} |
          {% endfor %}

    - name: Save security rules to Markdown file
      copy:
        content: '{{ rules_md }}'
        dest: '../configs/security_rules.md'
