---
- name: Fetch all security rules from PAN-OS Firewall
  hosts: '{{ target | default("firewall") }}'
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

    vsys: 'vsys1'
    rule_base: 'security'

  tasks:
    - name: Fetch all security rules
      paloaltonetworks.panos.panos_op:
        ip_address: '{{ device.ip_address }}'
        username: '{{ device.username }}'
        password: '{{ device.password }}'
        api_key: '{{ device.api_key }}'
        cmd: 'show running security-policy'
      register: result

    - name: Parse security rules XML
      community.general.xml:
        xmlstring: '{{ result.stdout_xml }}'
        xpath: '/response/result/member'
        content: text
      register: security_rules

    - name: Convert security rules to Markdown table
      set_fact:
        markdown_table: |
          | Rule Name | From Zone | To Zone | Source | Destination | Application/Service | Action |
          |-----------|-----------|---------|--------|-------------|----------------------|--------|
          {% for rule in security_rules.matches %}
          | {{ rule.member.split(';')[0].strip() }} | {{ (rule.member.split(';')[1].split()[1]).strip() }} | {{ (rule.member.split(';')[1].split()[3]).strip() }} | {{ (rule.member.split(';')[2].split('[')[1].split(']')[0]).strip() }} | {{ (rule.member.split(';')[3].split()[1]).strip() }} | {{ (rule.member.split(';')[4].split('[')[1].split(']')[0]).strip() }} | {{ rule.member.split(';')[5].split()[1].strip() }} |
          {% endfor %}