<<<<<<< HEAD
# plays/configure_interface.yml

- name: Configure Interface G0/1 on R1
  hosts: R1
  gather_facts: no
  vars:
    interface_name: "GigabitEthernet0/1"
    ip_address: "10.0.1.1"
    subnet_mask: "255.255.255.248"
  tasks:
    - name: Load interface configuration from template
      template:
        src: templates/Interfaces.j2
        dest: ../configs/Interfaces_R1.cfg

    - name: Apply interface configuration to device
      ios_config:
        src: ../configs/Interfaces_R1.cfg
        backup: yes

- name: Configure Interface G0/1 on R2
  hosts: R2
  gather_facts: no
  vars:
    interface_name: "GigabitEthernet0/1"
    ip_address: "10.0.1.2"
    subnet_mask: "255.255.255.248"
  tasks:
    - name: Load interface configuration from template
      template:
        src: templates/Interfaces.j2
        dest: ../configs/Interfaces_R2.cfg

    - name: Apply interface configuration to device
      ios_config:
        src: ../configs/Interfaces_R2.cfg
=======
# plays/configure_interface.yml

- name: Configure Interface G0/1 on R1
  hosts: R1
  gather_facts: no
  vars:
    interface_name: "GigabitEthernet0/1"
    ip_address: "10.0.1.1"
    subnet_mask: "255.255.255.248"
  tasks:
    - name: Load interface configuration from template
      template:
        src: templates/Interfaces.j2
        dest: ../configs/Interfaces_R1.cfg

    - name: Apply interface configuration to device
      ios_config:
        src: ../configs/Interfaces_R1.cfg
        backup: yes

- name: Configure Interface G0/1 on R2
  hosts: R2
  gather_facts: no
  vars:
    interface_name: "GigabitEthernet0/1"
    ip_address: "10.0.1.2"
    subnet_mask: "255.255.255.248"
  tasks:
    - name: Load interface configuration from template
      template:
        src: templates/Interfaces.j2
        dest: ../configs/Interfaces_R2.cfg

    - name: Apply interface configuration to device
      ios_config:
        src: ../configs/Interfaces_R2.cfg
>>>>>>> 9759c638c595a5f820f607fd57b556b2dc3b24bb
        backup: yes