<<<<<<< HEAD
---
- name: Configure VLANs on Network Devices
  hosts: LAB1
  gather_facts: no

  tasks:
    - name: Generate VLAN Configuration
      template:
        src: vlan_config.j2
        dest: "../configs/{{ inventory_hostname }}_vlan_config.txt"

    - name: Apply VLAN Configuration
      ios_config:
        src: "../configs/{{ inventory_hostname }}_vlan_config.txt"
      when: ansible_network_os == 'ios'
=======
---
- name: Configure VLANs on Network Devices
  hosts: LAB1
  gather_facts: no

  tasks:
    - name: Generate VLAN Configuration
      template:
        src: vlan_config.j2
        dest: "../configs/{{ inventory_hostname }}_vlan_config.txt"

    - name: Apply VLAN Configuration
      ios_config:
        src: "../configs/{{ inventory_hostname }}_vlan_config.txt"
      when: ansible_network_os == 'ios'
>>>>>>> 9759c638c595a5f820f607fd57b556b2dc3b24bb
