<<<<<<< HEAD
---
- name: Set Interface description based on CDP/LLDP discovery
  hosts: LAB1
  gather_facts: yes

  tasks:
    - name: Set IOS Interface Description
      ios_config:
        lines:
          - description Connected to {{ item.value[0].host }} via its {{ item.value[0].port }}
        parents: interface {{ item.key }}
        save_when: changed
      with_dict: "{{ansible_facts.net_neighbors }}"
=======
---
- name: Set Interface description based on CDP/LLDP discovery
  hosts: LAB1
  gather_facts: yes

  tasks:
    - name: Set IOS Interface Description
      ios_config:
        lines:
          - description Connected to {{ item.value[0].host }} via its {{ item.value[0].port }}
        parents: interface {{ item.key }}
        save_when: changed
      with_dict: "{{ansible_facts.net_neighbors }}"
>>>>>>> 9759c638c595a5f820f607fd57b556b2dc3b24bb
      when: ansible_network_os == 'ios'