---
name: test_lab Topology
description: Test Lab YAML12345
path: "/"
nodes:
  - name: leaf01
    template: viosl2
    image: viosl2-adventerprisek9-m.SSA.high_iron_20200929
    left: 50
    top: 135
    configuration:
      file: configs/test_leaf01.cfg
  - name: leaf02
    template: viosl2
    image: viosl2-adventerprisek9-m.SSA.high_iron_20200929
    left: 200
    top: 135
    configuration:
      template: iosl2.j2
      vars:
        hostname: leaf02
        management_address: 10.10.10.1
        management_vlan_id: 199
