name: LAB_IOSXE01
description: Test with IOSXE Image
path: "/"
nodes:
  - name: IOS_XE_LAB01_01
    template: csr1000v
    image: csr1000vng-universalk9.16.09.07.Fuji
    left: 50
    configuration:
      template: leaf_config.j2
      vars:
        hostname: IOS_XE_LAB01_01
        management_address: 10.199.2.1
        subnet_mask: 255.255.255.0
        gateway: 10.199.1.254
  - name: IOS_XE_LAB01_02
    template: csr1000v
    image: csr1000vng-universalk9.16.09.07.Fuji
    left: 200
    configuration:
      template: leaf_config.j2
      vars:
        hostname: IOS_XE_LAB01_02
        management_address: 10.199.2.2
        subnet_mask: 255.255.255.0
        gateway: 10.199.1.254
networks:
  - name: Management
    network_type: pnet9
    visibility: 1
links:
  network:
    - src: IOS_XE_LAB01_01
      src_label: GigabitEthernet1
      dst: Management
    - src: IOS_XE_LAB01_02
      src_label: GigabitEthernet1
      dst: Management
