---
# Generate and save config backup
- hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: Generate a configuration backup
      paloaltonetworks.panos.panos_op:
        provider:
          ip_address: "{{ device.ip_address }}"
          username: "{{ device.username }}"
          password: "{{ device.password }}"
          api_key: "{{ device.api_key }}"
        cmd: "show config running"
        cmd_is_xml: no
      register: config_backup

    - name: Save configuration backup to local file
      copy:
        content: "{{ config_backup.stdout }}"
        dest: "./config_backup.xml"
      when: config_backup.stdout is defined
