---
# fw_rules.yml - Create security rules on a PAN-OS device.
#
# Description
# ===========
#
# Quick examples of how to use the 'panos_security_rule' module to create security rules on a PAN-OS device.
#
# This playbook requires connection details for the device to be specified in the variables 'ip_address', 'username',
# and 'password'.  These may be defined as host variables (see `host_vars/firewall.yml` for an example) or
# extra vars.
#
# Modules Used
# ============
#
# panos_security_rule - https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_security_rule.html
#
# Usage
# =====
#
#   $ ansible-playbook -i inventory fw_rules.yml

- hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: Backup configuration from PAN Equipment
      connection: local
      check_mode: no
      uri:
        validate_certs: no
        url: "https://{{ansible_host}}/api/?type=config&action=show&key={{key_list.matches[0].key}}"
        return_content: yes
        method: GET
      register: configuration_string

    - name: Remove XML Header and Save file in {{configs_dir}}
      connection: local
      check_mode: no
      copy:
        content: "{{configuration_string['content']  | regex_replace('<response.*<result>') | regex_replace('</result></response>')}}"
        dest: "{{configs_dir}}{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}-config.xml"
