port_channel:
  number: 1
  mode: active
  ports:
    - GigabitEthernet1/2
    - GigabitEthernet1/3

lag_members:
  - GigabitEthernet1/2
  - GigabitEthernet1/3

hostname: R1

router_id: 1.1.1.1

trunk_ports:
  - GigabitEthernet0/2
  - GigabitEthernet0/3
  - GigabitEthernet1/0
