port_channel:
  number: 1
  mode: active
  ports:
    - GigabitEthernet1/2
    - GigabitEthernet1/1

lag_members:
  - GigabitEthernet1/2
  - GigabitEthernet1/1

hostname: R3_1

#OSPF
router_id: "3.3.3.3"
ospf_instance: 1
areas:
  1:
    interfaces:
      - name: "GigabitEthernet0/2"
        network: "10.0.0.0"
        wildcard: "0.0.0.3"
    password_protected: false
  2:
    interfaces:
      - name: "GigabitEthernet1/1"
        network: "10.0.0.8"
        wildcard: "0.0.0.3"
    password_protected: false
#    password: "ospfpass456"


trunk_ports:
  - GigabitEthernet1/0
  - Port-channel20

vtp_mode: server