---
- name: Configure VLANs on Network Devices
  hosts: LAB1
  gather_facts: no

  vars:
    vlans:
      - { id: 10, name: "Client" }
      - { id: 20, name: "IoT" }
      - { id: 30, name: "Server" }

  tasks:
    - name: Generate VLAN Configuration
      template:
        src: vlan_config.j2
        dest: "./configs/{{ inventory_hostname }}_vlan_config.txt"

    - name: Apply VLAN Configuration
      ios_config:
        src: "./configs/{{ inventory_hostname }}_vlan_config.txt"
      when: ansible_network_os == 'ios'
