---
- name: Check Cisco Switch Connectivity
  hosts: LAB1
  gather_facts: no

  tasks:
    - name: Remove IP address from GigabitEthernet1/2
      ios_config:
        lines:
          - no ip address
        parents: interface GigabitEthernet1/2
      when: ansible_network_os == 'ios'

    - name: Ping Test
      ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: Display Output
      debug:
        var: output.stdout_lines
