---
- name: Configure LACP Port-Channels on Cisco IOS Switches LAB1
  hosts: LAB1
  gather_facts: no

  tasks:
    - name: Create link aggregation group
      cisco.ios.ios_linkagg:
        group: 10
        state: present
        mode: active
        members:
          - GigabitEthernet1/2
          - GigabitEthernet1/3
     