# plays/configure_ospf.yml

- name: Configure OSPF on routers
  hosts: LAB1
  gather_facts: no
  vars:
    areas:
      0:
        - name: "GigabitEthernet1/0/1"
          network: "10.0.1.0"
          wildcard: "0.0.0.7"
  tasks:
    - name: Load OSPF configuration from template
      template:
        src: templates/ospf_config.j2
        dest: ../configs/{{ inventory_hostname }}_ospf.cfg
      vars:
        router_id: "{{ router_id }}"

    - name: Apply OSPF configuration to device
      ios_config:
        src: ../configs/{{ inventory_hostname }}_ospf.cfg
        backup: yes
