- name: Configure OSPF on routers
  hosts: LAB1
  gather_facts: no
  tasks:
    - name: Debug router variables
      debug:
        msg: "Router ID for {{ inventory_hostname }} is {{ hostvars[inventory_hostname]['router_id'] }}"

    - name: Load OSPF configuration from template
      template:
        src: templates/ospf_config_HV.j2
        dest: ../configs/{{ inventory_hostname }}_ospf.cfg
      vars:
        router_id: "{{ hostvars[inventory_hostname]['router_id'] }}"
        ospf_instance: "{{ hostvars[inventory_hostname]['ospf_instance'] }}"
        areas: "{{ hostvars[inventory_hostname]['areas'] }}"

    - name: Display generated OSPF configuration
      command: cat ../configs/{{ inventory_hostname }}_ospf.cfg
      register: ospf_config_content

    - name: Debug generated OSPF configuration
      debug:
        var: ospf_config_content.stdout

    - name: Apply OSPF configuration to device with diff check
      ios_config:
        src: ../configs/{{ inventory_hostname }}_ospf.cfg
        backup: yes
        match: exact
        diff_against: running
        diff_ignore_lines:
          - '^Building configuration'
          - '^Current configuration'
      register: config_diff

    - name: Display config differences
      debug:
        var: config_diff
