---
- name: Configure VLANs on Network Devices
  hosts: LAB1
  gather_facts: no

  tasks:
    - name: Generate VLAN Configuration
      template:
        src: vlan_config.j2
        dest: "./configs/{{ inventory_hostname }}_vlan_config.txt"

    - name: Apply VLAN Configuration
      ios_config:
        src: "/home/silvan_adm/Git/ENCOR_LAB/Ansible/Eve-NG/Labs/CCNP_LAB001/configs/{{ inventory_hostname }}_vlan_config.txt"
      when: ansible_network_os == 'ios'
