- name: Configure LACP Port-Channels
  hosts: LAB1
  gather_facts: no

  tasks:
    - name: Delete Etherchannel
      cisco.ios.ios_linkagg:
        group: 20
        state: absent

    - name: Create Etherchannel
      cisco.ios.ios_linkagg:
        group: 20
        state: present
        mode: active
        members: "{{ lag_members }}"
      tags:
        - create
