all:
  children:
    core:
      hosts:
        core_switch:
          ansible_host: 10.255.5.200  # Management-IP
    switches:
      hosts:
        switch01:
          ansible_host: 10.255.5.2  # Spezifische Management-IP
          core_interface: "GigabitEthernet0/1"
        switch02:
          ansible_host: 10.255.5.6
          core_interface: "GigabitEthernet0/2"
  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: your_password
    ansible_connection: network_cli
