port_channel:
  number: 1
  mode: active
  ports:
    - GigabitEthernet1/2
    - GigabitEthernet1/3

lag_members:
  - GigabitEthernet1/2
  - GigabitEthernet1/1

hostname: Eve-NG-Ansible_Lab1

trunk_ports:
  - GigabitEthernet0/2
  - Port-channel20
