---
ip_address: '10.0.0.11'
username: 'admin'
password: 'Sei8sam!'
api_key: 'LUFRPT1abUFTWVFKcDNoUm9ERHMwMFBOb2hlN3JET3M9YTRtVWcrWUFLWGNxT1gxOWI4QmdsaUwwTllMN3BsRkpGeHZpT3JmbVhuNDg2OUd3bTM5aUM2NGhKNnh5TjYyQw=='
